version: 2

functions:
  - name: safe_divide
    description: Safely divide numerator by denominator
    arguments:
      - name: numerator
        data_type: float64
      - name: denominator
        data_type: float64
    returns:
      data_type: float64
